### ISSUE TITLE
Bootstrap Error when load the page

### ISSUE THREAD

**Issue by szcc** [DataStewardshipPortal/dsp-common#287]
### What is your question?

I deployed DS-wizard to one of my linux server and when I try to load the page from URL: myserverip:8080. I got an error:
Bootstrap Error
Configuration cannot be loaded due to server unavailable.
Please, contact the application provider.

**Comment by krystofkomanec** [comment]
Solved via email

**Comment by szcc** [comment]
Hi Komanec,

I am still have the problem. I was out lastweek and will work on it today.

Sue

**Comment by vknaisl** [comment]
Hello Sue,

Please use our Discord (https://discord.gg/MW3H9tdMcT) where our community may help you. The GitHub mainly serves for reporting bugs.

Regards,
Vojtech

**Comment by szcc** [comment]
Thank you.
I try to claim an account but it shows I already have one. But I do not
remember my password. Is there a way for user to change password?


[image: image.png]

**Comment by szcc** [comment]
ok I got in.
